spring:
  datasource:
    username: sa 
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

route:
  from: file:data/from
  to: jdbc:dataSourceH2